name: 'Pipeline to Netlify'

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build Flutter
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
      #- run: flutter pub get
      #- run: flutter test
      - run: flutter build web

      - name: Deploy to Netlify 🚀
        uses: jsmrcaga/action-netlify-deploy@master
        with:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }} 
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }} 
          NETLIFY_DEPLOY_MESSAGE: "${{ github.event.head_commit.message }}"
          NETLIFY_DEPLOY_TO_PROD: ${{ github.event_name == 'push' && true || false }}
        
